/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsSkillAttributes struct {
	Strength *DungeonsandtrollsAttributes `json:"strength,omitempty"`
	Dexterity *DungeonsandtrollsAttributes `json:"dexterity,omitempty"`
	Inteligence *DungeonsandtrollsAttributes `json:"inteligence,omitempty"`
	Willpower *DungeonsandtrollsAttributes `json:"willpower,omitempty"`
	Constitution *DungeonsandtrollsAttributes `json:"constitution,omitempty"`
	SlashArmor *DungeonsandtrollsAttributes `json:"slashArmor,omitempty"`
	PiercingResist *DungeonsandtrollsAttributes `json:"piercingResist,omitempty"`
	FireResist *DungeonsandtrollsAttributes `json:"fireResist,omitempty"`
	PoisonResist *DungeonsandtrollsAttributes `json:"poisonResist,omitempty"`
	ElectricResist *DungeonsandtrollsAttributes `json:"electricResist,omitempty"`
	Life *DungeonsandtrollsAttributes `json:"life,omitempty"`
	Stamina *DungeonsandtrollsAttributes `json:"stamina,omitempty"`
	Mana *DungeonsandtrollsAttributes `json:"mana,omitempty"`
	Scalar *DungeonsandtrollsAttributes `json:"scalar,omitempty"`
}
