/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsCommandsBatch struct {
	Buy *DungeonsandtrollsIdentifiers `json:"buy,omitempty"`
	PickUp *DungeonsandtrollsIdentifier `json:"pickUp,omitempty"`
	Move *DungeonsandtrollsCoordinates `json:"move,omitempty"`
	Skill *DungeonsandtrollsSkillUse `json:"skill,omitempty"`
	Yell *DungeonsandtrollsMessage `json:"yell,omitempty"`
}
