/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsElements struct {
	Cold int32 `json:"cold,omitempty"`
	Fire int32 `json:"fire,omitempty"`
	Lightning int32 `json:"lightning,omitempty"`
	Poison int32 `json:"poison,omitempty"`
	Physical int32 `json:"physical,omitempty"`
}
