/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProtobufNullValue string

// List of protobufNullValue
const (
	NULL_VALUE_ProtobufNullValue ProtobufNullValue = "NULL_VALUE"
)
