/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsEvent struct {
	Message string `json:"message,omitempty"`
	Type_ *DungeonsandtrollsEventType `json:"type,omitempty"`
	Coordinates *DungeonsandtrollsCoordinates `json:"coordinates,omitempty"`
}
