/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsEventType string

// List of dungeonsandtrollsEventType
const (
	DAMAGE_DungeonsandtrollsEventType DungeonsandtrollsEventType = "DAMAGE"
	MESSAGE_DungeonsandtrollsEventType DungeonsandtrollsEventType = "MESSAGE"
	BUY_DungeonsandtrollsEventType DungeonsandtrollsEventType = "BUY"
	EQUIP_DungeonsandtrollsEventType DungeonsandtrollsEventType = "EQUIP"
	ERROR__DungeonsandtrollsEventType DungeonsandtrollsEventType = "ERROR"
)
