/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsEffect struct {
	MinDamage *DungeonsandtrollsElements `json:"minDamage,omitempty"`
	MaxDamage *DungeonsandtrollsElements `json:"maxDamage,omitempty"`
	Duration int32 `json:"duration,omitempty"`
	AreaOfEffect int32 `json:"areaOfEffect,omitempty"`
	Boosts *DungeonsandtrollsAttributes `json:"boosts,omitempty"`
	MinStats *DungeonsandtrollsStats `json:"minStats,omitempty"`
	MaxStats *DungeonsandtrollsStats `json:"maxStats,omitempty"`
}
