/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsCharacter struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Attributes *DungeonsandtrollsAttributes `json:"attributes,omitempty"`
	Money string `json:"money,omitempty"`
	Equip []DungeonsandtrollsItem `json:"equip,omitempty"`
	Score string `json:"score,omitempty"`
}
