/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsGameState struct {
	Map_ *DungeonsandtrollsMap `json:"map,omitempty"`
	Items []DungeonsandtrollsItem `json:"items,omitempty"`
	Character *DungeonsandtrollsCharacter `json:"character,omitempty"`
	CurrentPosition *DungeonsandtrollsCoordinates `json:"currentPosition,omitempty"`
	Tick string `json:"tick,omitempty"`
	// List of events which occurred in the previous tick. Useful for visualising effects, debugging and communication.
	Events []DungeonsandtrollsEvent `json:"events,omitempty"`
	Score string `json:"score,omitempty"`
}
