/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsItemType string

// List of dungeonsandtrollsItemType
const (
	NONE_DungeonsandtrollsItemType DungeonsandtrollsItemType = "none"
	HEAD_DungeonsandtrollsItemType DungeonsandtrollsItemType = "head"
	MAIN_HAND_DungeonsandtrollsItemType DungeonsandtrollsItemType = "mainHand"
	OFF_HAND_DungeonsandtrollsItemType DungeonsandtrollsItemType = "offHand"
	BODY_DungeonsandtrollsItemType DungeonsandtrollsItemType = "body"
	LEGS_DungeonsandtrollsItemType DungeonsandtrollsItemType = "legs"
	NECK_DungeonsandtrollsItemType DungeonsandtrollsItemType = "neck"
)
