/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsDamageType string

// List of dungeonsandtrollsDamageType
const (
	NONE_DungeonsandtrollsDamageType DungeonsandtrollsDamageType = "none"
	SLASH_DungeonsandtrollsDamageType DungeonsandtrollsDamageType = "slash"
	PIERCING_DungeonsandtrollsDamageType DungeonsandtrollsDamageType = "piercing"
	FIRE_DungeonsandtrollsDamageType DungeonsandtrollsDamageType = "fire"
	POISON_DungeonsandtrollsDamageType DungeonsandtrollsDamageType = "poison"
	ELECTRIC_DungeonsandtrollsDamageType DungeonsandtrollsDamageType = "electric"
)
