/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsCoordinates struct {
	Level int32 `json:"level,omitempty"`
	PositionX int32 `json:"positionX,omitempty"`
	PositionY int32 `json:"positionY,omitempty"`
}
