/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsSkillUse struct {
	SkillId string `json:"skillId,omitempty"`
	TargetId string `json:"targetId,omitempty"`
	Location *DungeonsandtrollsCoordinates `json:"location,omitempty"`
}
