/*
 * Dungeons and Trolls
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DungeonsandtrollsDroppable struct {
	Skill *DungeonsandtrollsSkill `json:"skill,omitempty"`
	Item *DungeonsandtrollsItem `json:"item,omitempty"`
	Monster *DungeonsandtrollsMonster `json:"monster,omitempty"`
	Decoration *DungeonsandtrollsDecoration `json:"decoration,omitempty"`
	Waypoint *DungeonsandtrollsWaypoint `json:"waypoint,omitempty"`
	Key *DungeonsandtrollsKey `json:"key,omitempty"`
}
